### ISSUE TITLE
error when compiling

### ISSUE THREAD

**Issue by muranava** [aidenbell/getdents#2]
hi get this error when compiling on OSX 10.11.4

```
getdents.c:43:24: error: use of undeclared identifier 'SYS_getdents'
       nread = syscall(SYS_getdents, fd, buf, BUF_SIZE);
                       ^
1 error generated.
```

thanks

**Comment by bhavikup** [comment]
This is meant for use with a linux system as it says in the description.

**Comment by aidenbell** [comment]
Guys, it could be made to work on OSX but I don't know if the OSX stdlib/kernel would work in such a way that it would have the same benefit that it does when using on Linux.

It'd be worth the work adding the macros and whatnot to get it compiling on OSX iff it can be shown to provide the same benefit.
